[package]
name = "iridium"
version = "0.1.0"
authors = ["Pietrino Atzeni <pietrino.atzeni@moneyfarm.com>"]
edition = "2018"

[dependencies]
nom = "^4.0"
clap = { version = "2.32", features = ["yaml"] }
